config/routes.rb
Ticketee::Application.routes.draw do

  devise_for :users

 root :to => "projects#index"

 resources :projects do
 	resources :tickets
 end

end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :name
  validates :name, :presence =>true
  has_many :tickets, :dependent => :delete_all
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  belongs_to :project
  belongs_to :user
  attr_accessible :description, :title ,:user
  validates :title, :presence => true
  validates :description, :presence => true,
  						  :length	=> { :minimum =>10 }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me,:admin
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  private
  	def authorize_admin!
  		authenticate_user!
  		unless current_user.admin?
  			flash[:alert]="You must be an admin to do that."
  			redirect_to root_path
  		end  		
  	end
  
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	before_filter :authorize_admin!, :except =>[:index,:show]
	before_filter :find_project,:only=>[:show,
										:edit,
										:update,
										:destroy]
	def index
		@projects=Project.all
	end	
	def new
		@project=Project.new		
	end
	def create
		@project=Project.new(params[:project])
		if @project.save
			flash[:notice]="Project has been created."
			redirect_to @project
		else
			flash[:alert]="Project has not been created."
			render :action=>"new"
		end
	end
	def show
	end
	def edit
	end
	def update
		if @project.update_attributes(params[:project])
			flash[:notice]="Project has been updated."
			redirect_to @project
		else
			flash[:alert]="Project has not been updated."
			render :action=>"edit"
		end
	end
	def destroy
		if @project.destroy
			flash[:notice]="Project has been deleted."
			redirect_to projects_path
		else
			flash[:alert]="Project has not been deleted"
			redirect_to projects_path
		end		
	end

private
def find_project
	@project=Project.find(params[:id])
	rescue ActiveRecord::RecordNotFound
		flash[:alert]="The project you were looking" +
					  " for could not be found."
	redirect_to projects_path

end

end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
	before_filter :authenticate_user!, :except => [:index,:show]
	before_filter :find_project
	before_filter :find_ticket, :only=>[:show,
										:edit,
										:update,
										:destroy]
	def new
		@ticket=@project.tickets.build
	end
	def create
		@ticket = @project.tickets.build(params[:ticket].merge!(:user => current_user))
        #@ticket = @project.tickets.build(params[:ticket])
        #@ticket.user=current_user

		if @ticket.save
			flash[:notice]="Ticket has been created."
			redirect_to [@project,@ticket]
		else
			flash[:alert]="Ticket has not been created."
			render :action => "new"
		end		
	end
	def show
		
	end
	def edit
		
	end
	def update
		if(@ticket.update_attributes(params[:ticket]))
			flash[:notice]="Ticket has been updated."
			redirect_to [@project,@ticket]
		else
			flash[:alert]="Ticket has not been updated."
			render :action=>"edit"
		end	
	end
	def destroy
		@ticket.destroy
		flash[:notice]="Ticket has been deleted."
		redirect_to @project		
	end


	private
		def find_project
			@project=Project.find(params[:project_id])
		end
		def find_ticket
			@ticket=@project.tickets.find(params[:id])			
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def title(*parts)
		unless parts.empty?
			content_for :title do
			(parts << "Ticketee").join(" - ") unless parts.empty?
			end
		end
	end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title>
	<% if content_for?(:title) %>
	<%= yield(:title) %>
	<% else %>
	Ticketee
	<% end %>
</title>

  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	
	<% if content_for?(:title) %>
	<%= yield(:title) %>
	<% else %>
	Ticketee
	<% end %>
<nav>
	<% if user_signed_in? %>
		Signed in as <%= current_user.email %>
	<%else%>
		<%= link_to "Sign up",new_user_registration_path %>
	<% end %>
	<%= link_to "Sign in", new_user_session_path %>
</nav>
<% flash.each do |key,value| %>
	<div class='flash' id='<%= key %>' >
		<%= value %>
	</div>
<%end%>
<h1><%=link_to "Ticketee",root_path %></h1>
<%= yield %>

</body>
</html>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
<%= f.error_messages %>
 <p>
 	<%=f.label :name%>
 	<%=f.text_field :name%>
 </p>
 <%=f.submit%>
<%end%>

app/views/projects/edit.html.erb
<h2>Edit Project</h2>
<%= render "form" %>

app/views/projects/index.html.erb
<%= link_to "New Project", new_project_path %>
<ul>
<% @projects.each do |project|%>
	<li><%= link_to project.name,project %></li>
<% end %>
</ul>

app/views/projects/new.html.erb
<h2>New Project</h2>
<%=render "form" %>

app/views/projects/show.html.erb
<h2><%=@project.name %></h2>
<% title(@project.name, "Projects") %>
<%= link_to "Edit Project", edit_project_path(@project)%>
<%= link_to "Delete Project",@project,:method => 'delete',:data => {:confirm => "Are you sure you want to delete this project?"} %>
<%= link_to "New Ticket",new_project_ticket_path(@project)%>
<ul id="tickets">
	<% @project.tickets.each do |ticket|%>
	<li>
		#<%=ticket.id %> - <%= link_to ticket.title,[@project,ticket] %>
	</li>
	<% end %>
</ul>

app/views/tickets/_form.html.erb
<%= form_for [@project, @ticket] do |f| %>

	<%= f.error_messages %>
	<p>
		<%= f.label :title %>
		<%= f.text_field :title %>
	</p>
	<p>
		<%= f.label :description %>
		<%= f.text_area :description %>
	</p>
	<%= f.submit %>
<% end%>

app/views/tickets/edit.html.erb
<h2>Editing a ticket in <%= @project.name %></h2>
<%= render "form" %>

app/views/tickets/new.html.erb
<h2>New Ticket</h2>
<%= render 'form' %>

app/views/tickets/show.html.erb
<div id='ticket'>
	<h2><%= @ticket.title %></h2>
	<%= simple_format(@ticket.description) %>
	<br><small>Created by <%= @ticket.user.email %></small>
	<%= link_to "Edit Ticket", [:edit,@project,@ticket] %>
</div>
<%= link_to "Delete Ticket",[@project,@ticket],:method=>:delete,:data => {:confirm=>"Are you sure you want to delete this ticket?"} %>

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>